### ISSUE TITLE
Check if one can authenticate using the keytabs

### ISSUE THREAD

**Issue by JAORMX** [JAORMX/tripleo-tls-everywhere-helper#11]
Currently, the playbook validates if the host keytab exists. It would be good to check if the keytab is actually valid and usable by kerberos; and not leftovers from a previous installation.

The idea would be to:
1. kinit using the keytab (and save the cache to a file)
2. Write the result to the report (success or failure)
3. Write a handler that does kdestroy on the cache, so we don't leave any leftovers on the host.

It would also be a good idea to piggy back this work and start checking novajoin's keytab as well.

**Comment by vakwetu** [comment]
This is resolved in set of commits on April 3
